import type { CatalogItem } from "./catalogTypes";

export const CATALOG_ITEMS: CatalogItem[] = [
  {
    id: "haproxy",
    slug: "haproxy",
    name: "HAProxy",
    kind: "service",
    category: "traffic",
    status: "available",
    summary: "L4/L7 load balancer with runtime control.",
    description:
      "Local dataplane load balancer for TCP and HTTP with TLS termination, health checks and runtime API.",
    version: "3.2.6",
    image: "haproxy",
    capabilities: ["L4", "L7", "TCP", "HTTP", "TLS termination", "health checks", "runtime API"],
    tags: ["lb", "proxy", "haproxy"],
    primaryAction: "create-instance",
    deployableServiceType: "haproxy",
    featured: true,
    brand: { monogram: "HA", accent: "traffic" },
    flowNodes: [
      { id: "vip", label: "VIP", role: "frontend" },
      { id: "hap", label: "HAProxy", role: "service" },
      { id: "pool", label: "Backends", role: "pool" },
    ],
    flowEdges: [
      { from: "vip", to: "hap", label: "HTTP/TCP" },
      { from: "hap", to: "pool", label: "roundrobin" },
    ],
  },
  {
    id: "frr",
    slug: "frr",
    name: "FRR",
    kind: "service",
    category: "traffic",
    status: "available",
    summary: "BGP routing and VIP advertisement.",
    description:
      "Free Range Routing for BGP route advertisement, looking glass and IPv4/IPv6 networking.",
    version: "10.2.6",
    image: "axionet/frr",
    capabilities: ["BGP", "route advertisement", "looking glass", "IPv4", "IPv6"],
    tags: ["bgp", "routing", "frr"],
    primaryAction: "create-instance",
    deployableServiceType: "frr",
    brand: { monogram: "FR", accent: "routing" },
    flowNodes: [
      { id: "peer", label: "BGP peer", role: "external" },
      { id: "frr", label: "FRR", role: "service" },
      { id: "vip", label: "VIP routes", role: "routes" },
    ],
    flowEdges: [
      { from: "peer", to: "frr", label: "BGP" },
      { from: "frr", to: "vip", label: "advertise" },
    ],
  },
  {
    id: "dnsdist",
    slug: "dnsdist",
    name: "dnsdist",
    kind: "service",
    category: "traffic",
    status: "planned",
    summary: "DNS load balancing, filtering and DoH/DoT.",
    description: "PowerDNS dnsdist for DNS load balancing, rate limiting, caching and encrypted DNS.",
    capabilities: ["DNS load balancing", "DNS filtering", "rate limiting", "caching", "DoT", "DoH", "metrics"],
    tags: ["dns", "dnsdist"],
    primaryAction: "create-service",
    brand: { monogram: "DD", accent: "core" },
  },
  {
    id: "varnish",
    slug: "varnish",
    name: "Varnish",
    kind: "service",
    category: "traffic",
    status: "planned",
    summary: "HTTP reverse proxy cache.",
    description: "Edge HTTP caching and reverse proxy for accelerating web content.",
    capabilities: ["HTTP cache", "reverse proxy", "edge caching"],
    tags: ["cache", "http"],
    primaryAction: "create-service",
    deployableServiceType: "varnish",
    brand: { monogram: "VA", accent: "traffic" },
    notes: [
      "Designer tree is published from packages/apps/varnish (axionet.app/v1).",
      "Runtime adapter not enabled yet (service definition remains disabled).",
    ],
    flowNodes: [
      { id: "listen", label: "Listen", role: "varnish-listen" },
      { id: "cache", label: "Cache", role: "varnish-cache" },
      { id: "origin", label: "Origin", role: "varnish-origin" },
    ],
    flowEdges: [
      { from: "listen", to: "cache", label: "vcl" },
      { from: "cache", to: "origin", label: "fetch" },
    ],
  },
  {
    id: "nginx",
    slug: "nginx",
    name: "Nginx",
    kind: "service",
    category: "traffic",
    status: "planned",
    summary: "Web server and reverse proxy.",
    description: "Nginx for static content, reverse proxy and web serving workloads.",
    capabilities: ["web server", "reverse proxy", "static content"],
    tags: ["http", "web"],
    primaryAction: "create-service",
    brand: { monogram: "NX", accent: "traffic" },
  },
  {
    id: "powerdns-auth",
    slug: "powerdns-auth",
    name: "PowerDNS Authoritative",
    kind: "core-service",
    category: "core",
    status: "planned",
    summary: "Authoritative DNS with REST API and GeoIP/Lua.",
    description:
      "Authoritative DNS server with REST API, DNSSEC, database backend, GeoIP and Lua Records for source-aware answers.",
    capabilities: [
      "authoritative DNS",
      "REST API",
      "DNSSEC",
      "database backend",
      "GeoIP",
      "Lua Records",
      "source-aware responses",
    ],
    tags: ["dns", "powerdns", "auth"],
    primaryAction: "create-service",
    brand: { monogram: "PD", accent: "core" },
    notes: [
      "PowerDNS Views are suitable for split-horizon, while Lua Records and GeoIP can drive source-, location- and health-aware answers.",
    ],
    experimentalFlags: ["Views (experimental)"],
    flowNodes: [
      { id: "client", label: "Client", role: "client" },
      { id: "auth", label: "Auth", role: "dns" },
      { id: "db", label: "DB", role: "store" },
    ],
    flowEdges: [
      { from: "client", to: "auth", label: "query" },
      { from: "auth", to: "db", label: "zones" },
    ],
  },
  {
    id: "powerdns-recursor",
    slug: "powerdns-recursor",
    name: "PowerDNS Recursor",
    kind: "core-service",
    category: "core",
    status: "planned",
    summary: "Recursive DNS with RPZ and Lua policy.",
    description: "Recursive resolver with DNSSEC validation, RPZ, Lua policy and caching.",
    capabilities: ["recursive DNS", "DNSSEC validation", "RPZ", "Lua policy", "caching"],
    tags: ["dns", "powerdns", "recursor"],
    primaryAction: "create-service",
    brand: { monogram: "PR", accent: "core" },
  },
  {
    id: "powerdns-platform",
    slug: "powerdns-platform",
    name: "PowerDNS Platform",
    kind: "stack",
    category: "core",
    status: "concept",
    summary: "Curated DNS stack: dnsdist + Auth + Recursor.",
    description:
      "Deploy dnsdist, PowerDNS Authoritative and Recursor together for split DNS, GeoDNS and health-aware answers.",
    capabilities: ["split DNS", "GeoDNS", "health-aware DNS", "source-aware policy", "DNSSEC", "RPZ"],
    components: [
      { id: "dnsdist", name: "dnsdist", role: "edge", required: true },
      { id: "auth", name: "PowerDNS Authoritative", role: "authoritative", required: true },
      { id: "rec", name: "PowerDNS Recursor", role: "recursive", required: true },
      { id: "db", name: "Database", role: "backend", required: false },
    ],
    dependencies: ["dnsdist", "powerdns-auth", "powerdns-recursor"],
    tags: ["dns", "stack", "powerdns"],
    primaryAction: "deploy-stack",
    featured: true,
    brand: { monogram: "PP", accent: "core" },
    notes: [
      "PowerDNS Views are suitable for split-horizon, while Lua Records and GeoIP can drive source-, location- and health-aware answers.",
      "Views remain documented as experimental — treat as design preview only.",
    ],
    experimentalFlags: ["Views (experimental)"],
    flowNodes: [
      { id: "client", label: "Client", role: "client" },
      { id: "dnsdist", label: "dnsdist", role: "edge" },
      { id: "auth", label: "Auth", role: "dns" },
      { id: "rec", label: "Recursor", role: "dns" },
      { id: "db", label: "DB", role: "store" },
    ],
    flowEdges: [
      { from: "client", to: "dnsdist", label: "DNS" },
      { from: "dnsdist", to: "auth", label: "auth" },
      { from: "dnsdist", to: "rec", label: "recurse" },
      { from: "auth", to: "db", label: "zones" },
    ],
  },
  {
    id: "keycloak-mgmt",
    slug: "keycloak-mgmt",
    name: "Keycloak (Management)",
    kind: "core-service",
    category: "core",
    status: "available",
    summary: "OIDC IdP for AxioNet platform login on the management network.",
    description:
      "Deploy Keycloak as a managed instance for management-GUI SSO. Attach only to management networks — not exposed to the internet. Realms alone do not provide network isolation.",
    version: "26.2.4",
    image: "quay.io/keycloak/keycloak",
    implementationHint: "Keycloak",
    capabilities: ["OIDC", "platform login", "groups → Operators", "TOTP (optional)", "management network only"],
    tags: ["identity", "keycloak", "oidc", "mgmt"],
    primaryAction: "create-instance",
    deployableServiceType: "keycloak-mgmt",
    featured: true,
    brand: { monogram: "KC", accent: "security" },
    notes: [
      "Attach only to networks of type management.",
      "Use Wire platform OIDC on the instance detail page after deploy.",
    ],
    flowNodes: [
      { id: "gui", label: "AxioNet GUI", role: "frontend" },
      { id: "kc", label: "Keycloak mgmt", role: "service" },
      { id: "ops", label: "Operators", role: "identity" },
    ],
    flowEdges: [
      { from: "gui", to: "kc", label: "OIDC" },
      { from: "kc", to: "ops", label: "groups" },
    ],
  },
  {
    id: "keycloak-apps",
    slug: "keycloak-apps",
    name: "Keycloak (Apps)",
    kind: "core-service",
    category: "core",
    status: "available",
    summary: "OIDC IdP for customer applications on app / dataplane networks.",
    description:
      "Separate Keycloak instance for app/customer authentication. Use multiple realms per tenant as needed. Do not share the management IdP with internet-facing apps.",
    version: "26.2.4",
    image: "quay.io/keycloak/keycloak",
    implementationHint: "Keycloak",
    capabilities: ["OIDC", "per-tenant realms", "app IdP", "dataplane networks"],
    tags: ["identity", "keycloak", "oidc", "apps"],
    primaryAction: "create-instance",
    deployableServiceType: "keycloak-apps",
    brand: { monogram: "KA", accent: "security" },
    notes: ["Attach to bridge/ipvlan/macvlan (or other non-mgmt) networks as appropriate."],
    flowNodes: [
      { id: "app", label: "Customer app", role: "frontend" },
      { id: "kc", label: "Keycloak apps", role: "service" },
    ],
    flowEdges: [{ from: "app", to: "kc", label: "OIDC" }],
  },
  {
    id: "auth-gateway",
    slug: "auth-gateway",
    name: "Auth Gateway",
    kind: "core-service",
    category: "security",
    status: "available",
    summary: "OIDC reverse proxy in front of legacy apps that cannot speak OIDC.",
    description:
      "oauth2-proxy security layer: users authenticate via Keycloak (apps), then traffic is proxied to the upstream with identity headers (X-Forwarded-User / Email / Groups). Point a HAProxy VIP at the gateway listen address.",
    version: "v7.8.1",
    image: "quay.io/oauth2-proxy/oauth2-proxy",
    implementationHint: "oauth2-proxy",
    capabilities: ["OIDC", "session cookie", "identity headers", "legacy front door"],
    tags: ["identity", "oauth2-proxy", "security", "gateway"],
    primaryAction: "create-instance",
    deployableServiceType: "auth-gateway",
    brand: { monogram: "AG", accent: "security" },
    notes: [
      "Requires a reachable Keycloak-apps issuer.",
      "Upstream is the legacy app URL (http://host:port).",
    ],
    flowNodes: [
      { id: "user", label: "User", role: "client" },
      { id: "gw", label: "Auth gateway", role: "security" },
      { id: "kc", label: "Keycloak apps", role: "service" },
      { id: "app", label: "Legacy app", role: "backend" },
    ],
    flowEdges: [
      { from: "user", to: "gw", label: "HTTPS" },
      { from: "gw", to: "kc", label: "OIDC" },
      { from: "gw", to: "app", label: "headers" },
    ],
  },
  {
    id: "pki-acme",
    slug: "pki-acme",
    name: "PKI / ACME",
    kind: "core-service",
    category: "core",
    status: "concept",
    summary: "Internal CA and automated certificate renewal.",
    description: "Internal certificate authority with ACME, renewal and mTLS trust distribution.",
    implementationHint: "step-ca",
    capabilities: ["internal CA", "ACME", "certificate renewal", "mTLS", "trust distribution"],
    tags: ["pki", "acme", "tls"],
    primaryAction: "create-service",
    brand: { monogram: "CA", accent: "security" },
  },
  {
    id: "coraza-waf",
    slug: "coraza-waf",
    name: "Coraza WAF",
    kind: "service",
    category: "security",
    status: "concept",
    summary: "OWASP CRS web application firewall.",
    description: "Request filtering WAF with OWASP CRS and audit events for HTTP frontends.",
    capabilities: ["WAF", "OWASP CRS", "request filtering", "audit events"],
    tags: ["waf", "security"],
    primaryAction: "create-service",
    brand: { monogram: "WZ", accent: "security" },
  },
  {
    id: "secure-web-frontend",
    slug: "secure-web-frontend",
    name: "Secure Web Frontend",
    kind: "blueprint",
    category: "security",
    status: "concept",
    summary: "HAProxy + auth-gateway + TLS (WAF optional later).",
    description:
      "Blueprint for a hardened web frontend. Today: deploy Keycloak (Apps) + Auth Gateway, then point HAProxy VIP at the gateway. WAF/MFA remain future components.",
    capabilities: ["TLS", "auth gateway", "rate limiting", "MFA optional", "monitoring"],
    components: [
      { id: "hap", name: "HAProxy", role: "frontend", required: true },
      { id: "gw", name: "Auth Gateway", role: "auth", required: true },
      { id: "kc", name: "Keycloak (Apps)", role: "auth", required: true },
      { id: "waf", name: "Coraza WAF", role: "security", required: false },
      { id: "cert", name: "Certificate", role: "tls", required: true },
    ],
    tags: ["blueprint", "web", "security"],
    primaryAction: "start-wizard",
    brand: { monogram: "SW", accent: "blueprint" },
    notes: ["Related deployables: keycloak-apps and auth-gateway (available now)."],
    flowNodes: [
      { id: "user", label: "User", role: "client" },
      { id: "hap", label: "HAProxy", role: "lb" },
      { id: "gw", label: "Auth gateway", role: "security" },
      { id: "app", label: "App", role: "backend" },
    ],
    flowEdges: [
      { from: "user", to: "hap", label: "HTTPS" },
      { from: "hap", to: "gw", label: "HTTP" },
      { from: "gw", to: "app", label: "headers" },
    ],
  },
  {
    id: "prometheus",
    slug: "prometheus",
    name: "Prometheus",
    kind: "service",
    category: "observability",
    status: "planned",
    summary: "Metrics collection and alerting rules.",
    description: "Time-series metrics for dataplane and control-plane observability.",
    capabilities: ["metrics", "scrape", "alerting rules"],
    tags: ["metrics", "observe"],
    primaryAction: "create-service",
    brand: { monogram: "PM", accent: "observe" },
  },
  {
    id: "alertmanager",
    slug: "alertmanager",
    name: "Alertmanager",
    kind: "service",
    category: "observability",
    status: "planned",
    summary: "Alert routing and notification.",
    description: "Routes and silences alerts from Prometheus to operators.",
    capabilities: ["alert routing", "silences", "notifications"],
    tags: ["alerts", "observe"],
    primaryAction: "create-service",
    brand: { monogram: "AM", accent: "observe" },
  },
  {
    id: "grafana",
    slug: "grafana",
    name: "Grafana",
    kind: "service",
    category: "observability",
    status: "planned",
    summary: "Dashboards for metrics and logs.",
    description: "Visualization and dashboards for Prometheus, Loki and related sources.",
    capabilities: ["dashboards", "Explore", "alerting UI"],
    tags: ["dashboards", "observe"],
    primaryAction: "create-service",
    brand: { monogram: "GF", accent: "observe" },
  },
  {
    id: "loki",
    slug: "loki",
    name: "Loki",
    kind: "service",
    category: "observability",
    status: "concept",
    summary: "Log aggregation for instances and platform.",
    description: "Log aggregation aligned with Prometheus-style labels.",
    capabilities: ["log aggregation", "label queries"],
    tags: ["logs", "observe"],
    primaryAction: "create-service",
    brand: { monogram: "LK", accent: "observe" },
  },
  {
    id: "monitoring-stack",
    slug: "monitoring-stack",
    name: "Monitoring Stack",
    kind: "stack",
    category: "observability",
    status: "concept",
    summary: "Prometheus, Alertmanager, Grafana and Loki.",
    description: "Curated observability stack covering node, HAProxy and FRR metrics plus logs.",
    capabilities: ["metrics", "alerts", "dashboards", "logs"],
    components: [
      { id: "prom", name: "Prometheus", role: "metrics", required: true },
      { id: "am", name: "Alertmanager", role: "alerts", required: true },
      { id: "gf", name: "Grafana", role: "ui", required: true },
      { id: "loki", name: "Loki", role: "logs", required: false },
    ],
    tags: ["stack", "observe"],
    primaryAction: "deploy-stack",
    brand: { monogram: "MS", accent: "observe" },
    flowNodes: [
      { id: "targets", label: "Targets", role: "source" },
      { id: "prom", label: "Prometheus", role: "metrics" },
      { id: "gf", label: "Grafana", role: "ui" },
      { id: "am", label: "Alertmanager", role: "alerts" },
    ],
    flowEdges: [
      { from: "targets", to: "prom", label: "scrape" },
      { from: "prom", to: "gf", label: "query" },
      { from: "prom", to: "am", label: "alerts" },
    ],
  },
  {
    id: "guacamole",
    slug: "guacamole",
    name: "Apache Guacamole",
    kind: "blueprint",
    category: "blueprints",
    status: "concept",
    summary: "Browser-based remote access blueprint.",
    description:
      "Multi-component remote desktop gateway with guacd, database, HAProxy frontend and optional MFA.",
    capabilities: ["RDP/VNC/SSH", "browser client", "TLS", "optional MFA"],
    components: [
      { id: "web", name: "Guacamole web", role: "app", required: true },
      { id: "guacd", name: "guacd", role: "daemon", required: true },
      { id: "db", name: "PostgreSQL/MariaDB", role: "store", required: true },
      { id: "hap", name: "HAProxy", role: "frontend", required: true },
      { id: "cert", name: "TLS certificate", role: "tls", required: true },
      { id: "mfa", name: "Identity & MFA", role: "auth", required: false },
    ],
    tags: ["blueprint", "remote", "guacamole"],
    primaryAction: "start-wizard",
    featured: true,
    brand: { monogram: "GQ", accent: "blueprint" },
    flowNodes: [
      { id: "user", label: "Browser", role: "client" },
      { id: "hap", label: "HAProxy", role: "lb" },
      { id: "web", label: "Guacamole", role: "app" },
      { id: "guacd", label: "guacd", role: "daemon" },
      { id: "target", label: "RDP/SSH", role: "target" },
    ],
    flowEdges: [
      { from: "user", to: "hap", label: "HTTPS" },
      { from: "hap", to: "web", label: "HTTP" },
      { from: "web", to: "guacd", label: "guac" },
      { from: "guacd", to: "target", label: "session" },
    ],
  },
  {
    id: "horizon-uag",
    slug: "horizon-uag",
    name: "Omnissa Horizon UAG",
    kind: "integration",
    category: "blueprints",
    status: "concept",
    summary: "LB integration for existing Horizon UAG.",
    description:
      "Configures VIP, HAProxy frontend and UAG backend pool against an existing Horizon/UAG deployment — AxioNet does not install the full Horizon platform.",
    capabilities: ["external VIP", "UAG pool", "health checks", "source persistence", "TLS", "monitoring"],
    components: [
      { id: "vip", name: "External VIP", role: "vip", required: true },
      { id: "hap", name: "HAProxy", role: "frontend", required: true },
      { id: "uag", name: "UAG pool", role: "backend", required: true },
    ],
    requirements: ["Existing Horizon / UAG deployment"],
    tags: ["integration", "horizon", "uag"],
    primaryAction: "configure-integration",
    brand: { monogram: "HZ", accent: "blueprint" },
    notes: [
      "AxioNet configures load balancing and integration toward existing Horizon/UAG, not a full Horizon install.",
    ],
    flowNodes: [
      { id: "client", label: "Client", role: "client" },
      { id: "vip", label: "VIP", role: "vip" },
      { id: "hap", label: "HAProxy", role: "lb" },
      { id: "uag", label: "UAG", role: "external" },
    ],
    flowEdges: [
      { from: "client", to: "vip", label: "HTTPS" },
      { from: "vip", to: "hap", label: "L7" },
      { from: "hap", to: "uag", label: "pool" },
    ],
  },
  {
    id: "geo-redundant-lb",
    slug: "geo-redundant-lb",
    name: "Geo-redundant Load Balancer",
    kind: "blueprint",
    category: "blueprints",
    status: "concept",
    summary: "Multi-site HAProxy with BGP and optional DNS.",
    description: "Blueprint for HAProxy across sites with FRR/BGP withdrawal, sync and optional PowerDNS or Cloudflare.",
    capabilities: ["multi-site", "BGP", "health withdrawal", "optional DNS", "observability"],
    components: [
      { id: "hap", name: "HAProxy nodes", role: "lb", required: true },
      { id: "frr", name: "FRR / BGP", role: "routing", required: true },
      { id: "dns", name: "PowerDNS / Cloudflare", role: "dns", required: false },
    ],
    tags: ["blueprint", "ha", "geo"],
    primaryAction: "start-wizard",
    brand: { monogram: "GR", accent: "blueprint" },
  },
  {
    id: "ha-dns",
    slug: "ha-dns",
    name: "Highly Available DNS",
    kind: "blueprint",
    category: "blueprints",
    status: "concept",
    summary: "HA dnsdist + PowerDNS with optional BGP.",
    description: "Blueprint for redundant DNS edges with auth/recursor backends and health checks.",
    capabilities: ["HA DNS", "health checks", "optional BGP"],
    components: [
      { id: "dnsdist", name: "dnsdist nodes", role: "edge", required: true },
      { id: "auth", name: "PowerDNS Authoritative", role: "auth", required: true },
      { id: "rec", name: "PowerDNS Recursor", role: "rec", required: true },
    ],
    tags: ["blueprint", "dns", "ha"],
    primaryAction: "start-wizard",
    brand: { monogram: "HD", accent: "core" },
  },
  {
    id: "generic-web",
    slug: "generic-web",
    name: "Generic Web Application",
    kind: "blueprint",
    category: "blueprints",
    status: "concept",
    summary: "Wizard for VIP, TLS, pool and optional WAF/MFA.",
    description: "Generic blueprint steps for publishing a web application behind AxioNet.",
    capabilities: ["VIP", "TLS", "backend pool", "health check", "optional WAF", "optional MFA"],
    tags: ["blueprint", "web"],
    primaryAction: "start-wizard",
    brand: { monogram: "GW", accent: "blueprint" },
  },
  {
    id: "generic-tcp",
    slug: "generic-tcp",
    name: "Generic TCP Service",
    kind: "blueprint",
    category: "blueprints",
    status: "concept",
    summary: "Wizard for TCP VIP, pool and optional BGP.",
    description: "Generic blueprint for TCP listeners with health checks and optional PROXY protocol.",
    capabilities: ["VIP", "TCP", "health check", "optional PROXY", "optional BGP"],
    tags: ["blueprint", "tcp"],
    primaryAction: "start-wizard",
    brand: { monogram: "GT", accent: "blueprint" },
  },
  {
    id: "cloudflare",
    slug: "cloudflare",
    name: "Cloudflare",
    kind: "provider",
    category: "providers",
    status: "disconnected",
    connectionState: "disconnected",
    summary: "External DNS, LB and Tunnel via API account.",
    description:
      "Cloudflare is consumed as an external provider (DNS, Load Balancing, pools/origins, monitors, Tunnel) — not as a local dataplane container.",
    capabilities: [
      "DNS zones and records",
      "proxied DNS records",
      "Load Balancing",
      "pools and origins",
      "health monitors",
      "steering policies",
      "Cloudflare Tunnel",
      "Cloudflare Access",
    ],
    tags: ["provider", "cloudflare", "dns"],
    primaryAction: "connect-provider",
    featured: true,
    brand: { monogram: "CF", accent: "provider" },
    notes: ["Credentials are never stored by this mockup."],
    flowNodes: [
      { id: "ax", label: "AxioNet", role: "control" },
      { id: "cf", label: "Cloudflare API", role: "provider" },
      { id: "edge", label: "CF edge", role: "edge" },
      { id: "origin", label: "Origin / Tunnel", role: "origin" },
    ],
    flowEdges: [
      { from: "ax", to: "cf", label: "API" },
      { from: "edge", to: "origin", label: "traffic" },
    ],
  },
];

export function getCatalogItemBySlug(slug: string): CatalogItem | undefined {
  return CATALOG_ITEMS.find((item) => item.slug === slug || item.id === slug);
}
